---
- name: demo on register and debug module
  hosts: all
  become: yes
  tasks:
    - name: use stat module
      stat:
        path: /tmp/myfile.txt
      register: isexists
    - debug: var=isexists

    - name: copy the contentinto files
      copy:
        content: "hiiiii this is veera whos there"
        dest: /tmp/myfile.txt
      when: isexists.dev == "51713"