---
- name: thi is copy yml file
  hosts: all
  become: yes
  tasks:
    - copy:
        src: /etc/passwd
        dest: /tmp
        owner: veera
        group: veera
        mode: 0777

    - file:
        path: /tmp/ansible
        state: directory
    
    - apt:
        name: tree
        update_cache: yes
        state: present
