---
- name: diff tasks avalible
  hosts: all
  become: yes
  tasks: 
    - copy:
        src: /etc/passwd
        dest: /tmp

    - file:
        path: /tmp/ansible/veeranji
        state: touch
        mode: 0777
    
    - apt: 
          name: tree
          update_cache: yes
          state: absent
          autoremove: yes
    
    - apt: 
        name: apache2
        update_cache: yes
        state: absent
        autoremove: yes

