---
- name: install java
  hosts: all
  become: yes
  tasks:
    - name: installing java 1.8
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: absent
        autoremove: yes