---
- name: install java
  hosts: all
  become: yes
  tasks:
    - name: install java 1.8 on debian os
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when: ansible_facts ['os_family'] =="debian"