---
- name: thi is copy yml file
  hosts: all
  become: yes
  tasks:
    - name: install tree
      apt:
        name: tree
        state: present 
    - apt: 
        name: apache2
        update_cache: yes
        state: present
        