---
- name: install pkgs
  hosts: all
  become: yes
  tasks:
    - name: install multiple pkgs
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - apache2
        - wget
        - tree
        - openjdk-8-jdk
        - maven
        - git